### ISSUE TITLE
Webinar dates are missing

### ISSUE THREAD

**Issue by MirzaazriM** [edudip/edudip-next-api#1]
If I send POST request, for creating a webinar, as this one:
{
	"title": "Webinar",
	"max_participants": 20,
	"recording": 0,
	"registration_type": "series",
	"access": "all",
	"dates": [{
		"date": "2019-14-11 09:05:00",
		"duration": 50
	}],
	"language": "en"
}

I get error "Webinar dates are missing". Is the "dates" key for dates array valid?

**Comment by marc-steinert** [comment]
Your input values look correct.
Are you sending those values as JSON encoded data in the HTTP body? The data needs to be sent as form data.

<img width="1245" alt="Bildschirmfoto 2019-11-07 um 13 26 36" src="https://user-images.githubusercontent.com/614366/68389210-b5fe8300-0162-11ea-9165-d9edab52b892.png">

**Comment by MirzaazriM** [comment]
I was sending data in JSON format. After setting them as form data request passed. Thanks.
