### ISSUE TITLE
next_date missing

### ISSUE THREAD

**Issue by Prinzhorn** [edudip/edudip-next-api#2]
> The returned webinar object is _largely_ identical to the webinar object that is delivered via the GET /api/webinars endpoint, although the following values are also delivered:

> Das zurückgelieferte Webinar-Objekt ist _weitesgehend_ identisch mit dem Webinar-Objekt, dass über den Endpunkt GET /api/webinars ausgeliefert wird, es werden jedoch noch folgende Werte zusätzlich ausgeliefert:

_largely_ and _weitesgehend_ are somewhat vague. `next_date` is missing from `GET /api/webinars/[Webinar-Id]` but included in `GET /api/webinars` is this expected behavior? I'd expect both to return the exact same properties and `GET /api/webinars/[Webinar-Id]` to have _additional_ properties that would otherwise make the list from `GET /api/webinars` too verbose. I would not expect properties to be missing.

Edit: `landingpage` is also missing, all other properties are there.

These properties are not documented at all:

```
clients_id
deadline_minutes
is_chargeable
price_gross
price_net
ratings_active
room_auth_link
show_cancel_registration
user
webinars_categories_id
```

**Comment by bvdh82** [comment]
Hi, 

thanks for your issue. 

We will include `next_date` and `landingpage` in GET `/api/webinars/[Webinar-Id]` in the future. 

Also we will remove the undocumented properties or include them into our documentation. 

Best
Bodo.
