### ISSUE TITLE
Timezones?

### ISSUE THREAD

**Issue by Prinzhorn** [edudip/edudip-next-api#3]
The API doesn't seem to be aware that timezones exist. At the same time Webinars make it easy to work with people around the world. Right now it looks like all dates are UTC/GMT +1, but I can only guess/hope that it's always that way even with daylight savings time? It would be great if timezone infos could be added to the documentation and maybe next² could use UTC?

The format strings in the documentation are also inconsistent, but I assume that's just a typo? Different libraries use different format strings anyway, so they are not of much help without specifying which standard they refer to. E.g. in [date-fns](https://date-fns.org/v2.16.1/docs/format) `ii` is `ISO day of week`, which is _probably_ not what's meant here.

> Time of creation of the webinar in the form **YYYY-MM-DD HH:ii:ss**

> Date and time when the appointment should take place. Format: **YYYY-MM-DD HH:MM:SS** (e.g. 2019-12-01 12:30:00)

Let's say edudip was written in Java, a short snipped how to create and parse the date strings the API expects would go a long way. So even if I'm using a different implementation I'd still have some sort of reference point.

**Comment by bvdh82** [comment]
Hi, 

you're right, the timezone information is missing. Currently all times uses 'Europe/Berlin' as timezone. We think about adding this information in the response or just adding it to the documentation.  

In our reference implementation [https://github.com/edudip/next-api-client](https://github.com/edudip/next-api-client) you can see that always the PHP-format `Y-m-d H:i:s` is used. But you are right, we will change this in our documentation. 

Many thanks for your feedback!

Best
Bodo

**Comment by Prinzhorn** [comment]
Thanks for your response!

If I understand correctly your reference implementation only works when the PHP script is run on a server that is configured for `Europe/Berlin`. Correct? Otherwise this https://github.com/edudip/next-api-client/blob/43b557ab7e25b30783b1ef9995fcc89c12aa9bb0/src/Edudip/Next/ApiClient/WebinarDate.php#L76 will turn the string into a _local_ DateTime object since the date string is missing timezone information. Currently in my PHP wrapper I'm using something like this to provide UTC versions of the strings that the API provides so that I can consume the dates on the client without pain.

```php
function toUTC($date_str) {
    date_default_timezone_set('Europe/Berlin');
    $datetime = new DateTime($date_str);
    return $datetime->format('c');
}
```

Honestly this timezone stuff is confusing and I'm just advocating that everyone uses UTC in their database and API design.

Edit: So you could actually add UTC in a backwards compatible way like I do. I provide properties like `next_date_utc` in addition to the original. You could do the same for `/register-participant` and add `webinar_date_utc`
