### ISSUE TITLE
Not all params from original edudip.com webinar-registration form can be passed via API

### ISSUE THREAD

**Issue by sulman8s** [edudip/edudip-next-api#4]
Hey,

According the edudip API documentation, we can pass only following parameters for the webinar registration.

Parameter | Data type | Required | Description
-- | -- | -- | --
email | String | ✓ | Participant's email address
firstname | String | ✓ | Forename of the participant
lastname | String | ✓ | Surname of the participant
webinar_date | String | ✕ | Date in the format Y-m-d H:i:s (i.g. 2019-12-01 12:30:00), if you wish to register for one date only (if property registration_type of the webinar is set to ```date`` (single appointment)).

Reference: 
https://github.com/edudip/edudip-next-api/blob/master/edudip-next-api-documentation-en.md#register-a-participant-for-a-webinar

**Is it possible to pass parameters like on https://www.edudip.com with API?**
If not, will it be available in the near future? 

Screenshot from edudip.com
![edudip com_register_form](https://user-images.githubusercontent.com/2495429/107493429-e155f600-6b8d-11eb-82e1-1d9ba18dba41.jpg)

Thanks

**Comment by saitho** [comment]
Do you plan on extending the API so we can set additional fields via the registration API as shown above?

cc @bvdh82 @marc-steinert

**Comment by saitho** [comment]
@bvdh82 I saw you added a "registration_fields" property to the webinar endpoint.
Is this also available when registering a participant via the API; and it's just not documented here?
Think that would solve this issue, thanks!

**Comment by bvdh82** [comment]
Hi, it is possible/recommended to set the "registration_fields" during the registration (until now it is not documented). In next release (in 2-3 weeks) we will add the participants values of the registration_fields in /api/webinars/[Webinar-Id]-Endpoint. After that we will document it.
